---
# tasks file for logstash

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: logstash

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: logstash

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: logstash

- name: Create Logstash defaults file
  template: >
    src=logstash.default.j2
    dest=/etc/default/logstash
    owner=root
    group=root
    mode=0664
  notify: restart logstash
  tags: logstash

- name: Create Logstash configuration file
  template: >
    src=logstash.conf.j2
    dest=/etc/logstash/conf.d/logstash.conf
    owner=root
    group=root
    mode=0664
  notify: restart logstash
  tags: logstash

- name: Ensure Logstash service is started and enabled on boot
  service: name={{ logstash_service_name }} state=started enabled=yes
  tags: logstash
