---
# tasks file for logstash (Ubuntu specific)

- name: Install Elasticsearch PGP key
  apt_key: >
    url=https://packages.elastic.co/GPG-KEY-elasticsearch
    state=present
  tags: logstash

- name: Add Logstash 1.4 repository
  apt_repository: >
    repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main'
    state=present
  tags: logstash

- name: Add Logstash 1.5 repository
  apt_repository: >
    repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main'
    state=present
  tags: logstash

- name: Install Logstash <= 1.4 packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: logstash_packages_1_4
  when: logstash_version | version_compare('1.5', operator='lt')
  tags: logstash

- name: Install Logstash >= 1.5 packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: logstash_packages_1_5
  when: logstash_version | version_compare('1.5', operator='ge')
  tags: logstash
